### ISSUE TITLE
Meta: list of things we need to mention in the FAQ

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#505]
* [ ] Why do single brands have many prices per unit? #476 
* [ ] Licensing issues #468 
* [ ] Impossible or improbable savings #492 (including specials: #457)
* [ ] Bioequivalence #462 
* [ ] Changing DT prices #466
